apiVersion: v1
kind: Service
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
    - name: ftps
      port: 21
      targetPort: 21
    - name: begin
      port: 21000
      targetPort: 21000
    - name: end
      port: 21001
      targetPort: 21001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ft_ftps
          imagePullPolicy: Never