apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
  ports:
    - name: http
      port: 5050
      targetPort: 5050
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      volumes:
        - name: wordpress-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: wordpress
          image: ft_wordpress
          imagePullPolicy: Never
          volumeMounts:
            - name: wordpress-pv-storage
              mountPath: "/var/lib/mysql"
