apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: phpmyadmin
  selector:
    app: phpmyadmin
    tier: mysql
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
        tier: mysql
    spec:
      containers:
        - name: phpmyadmin
          image: ft_phpmyadmin
          ports:
            - containerPort: 5000
              name: phpmyadmin
          env:
            - name: PMA_HOST
              value: mysql
            - name: PMA_PORT
              value: "3306"
            - name: PMA_USER
              value: admin
            - name: MYSQL_ROOT_PASSWORD
              value: password
          imagePullPolicy: Never
