apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: wordpress
spec:
  type: LoadBalancer
  selector:
    app: wordpress
    tier: wordpress
  ports:
    - name: http
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      volumes:
        - name: phpmyadmin-pv-storage
          persistentVolumeClaim:
            claimName: mysql-pvc
      containers:
        - name: phpmyadmin
          image: ft_phpmyadmin
          imagePullPolicy: Never
          volumeMounts:
            - name: phpmyadmin-pv-storage
              mountPath: "/var/lib/mysql"
